FROM ruby:2.3.0-alpine
MAINTAINER sheaphillips <shea.phillips@gmail.com>

RUN apk update \
  && apk add ruby-dev libpq libgcc ca-certificates make gcc libc-dev libffi-dev \
             nodejs 'python<3' zlib-dev libxml2 libxml2-dev libxslt libxslt-dev \
  && gem install nokogiri -- --use-system-libraries -N \
  && gem install jekyll -N \
  && gem install github-pages -N \
  && apk del --purge ruby-dev \
                     libgcc gcc make libc-dev libffi-dev zlib-dev libxml2-dev libxslt-dev \
  && apk add ruby-json

RUN mkdir /guide && mkdir /guide/_site

ADD Gem* /guide/

WORKDIR /guide

RUN bundler

VOLUME /guide

ENV POLLING=true

EXPOSE 4000

CMD ./go serve --host 0.0.0.0
